version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    networks:
      - mynetwork
    entrypoint: ["/app/entrypoint.sh"]
    command: ["server"]

volumes:
  dbdata:

networks:
  mynetwork:
    driver: bridge